### ISSUE TITLE
localhost:8081 unavailable

### ISSUE THREAD

**Issue by JorisHeadease** [Koppeltaal/KT2-Docker-Compose#1]
Sometimes after `docker compose up` domain-admin is not responding even though it started up. 

Current workaround is executing `docker compose restart domain-admin`

**Comment by janwijbrand** [comment]
I can concur - sometimes a restart works, but a lot of times even many restarts do not give a running setup.

**Comment by JorisHeadease** [comment]
Probably related to #3

**Comment by JorisHeadease** [comment]
This issue seems to be resolved along the other fixes.
